import { AppState } from "./types";

// 演示种子数据（直接构造，时间为相对今天的历史记录）
function daysAgoIso(days: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export function seedState(): AppState {
  return {
    rooms: [
      { id: "CR-1201", isoClass: "ISO 5", dpLimit: 180 },
      { id: "CR-2107", isoClass: "ISO 6", dpLimit: 200 },
      { id: "Y-0302", isoClass: "黄光区", dpLimit: 220 },
    ],
    filters: [
      { id: "HEPA-01", roomId: "CR-1201", spec: "H14", installBatchId: "B2026-01" },
      { id: "HEPA-02", roomId: "CR-2107", spec: "H13", installBatchId: "B2026-02" },
      { id: "HEPA-03", roomId: "Y-0302", spec: "H13", installBatchId: "B2026-02" },
      { id: "HEPA-04", roomId: "CR-1201", spec: "H14", installBatchId: "B2025-09" },
    ],
    batches: [
      { id: "B2025-09", spec: "H14", totalQty: 2, inboundAt: "2025-09-02", expiry: "2026-09-01" },
      { id: "B2026-01", spec: "H14", totalQty: 2, inboundAt: "2026-01-10", expiry: "2027-01-10" },
      { id: "B2026-02", spec: "H13", totalQty: 3, inboundAt: "2026-02-05", expiry: "2027-03-05" },
      { id: "B2026-04", spec: "H14", totalQty: 1, inboundAt: "2026-04-18", expiry: "2026-10-15" },
      { id: "B2026-05", spec: "H14", totalQty: 4, inboundAt: "2026-05-20", expiry: "2027-05-20" },
      { id: "B2026-06", spec: "H13", totalQty: 2, inboundAt: "2026-06-12", expiry: "2027-06-12" },
    ],
    inspections: [
      {
        id: "INSP-SEED-0101",
        filterId: "HEPA-01",
        roomId: "CR-1201",
        reading: 120,
        runningHours: 4200,
        equipmentStatus: "正常运行",
        note: "例行巡检",
        inspector: "巡检员",
        createdAt: daysAgoIso(20),
        revisions: [],
      },
      {
        id: "INSP-SEED-0102",
        filterId: "HEPA-01",
        roomId: "CR-1201",
        reading: 146,
        runningHours: 4520,
        equipmentStatus: "正常运行",
        note: "阻力抬升，持续观察",
        inspector: "巡检员",
        createdAt: daysAgoIso(10),
        revisions: [],
      },
      {
        id: "INSP-SEED-0103",
        filterId: "HEPA-01",
        roomId: "CR-1201",
        reading: 171,
        runningHours: 4810,
        equipmentStatus: "带病运行",
        note: "连续上升，已自动建单",
        inspector: "巡检员",
        createdAt: daysAgoIso(2),
        revisions: [],
      },
      {
        id: "INSP-SEED-0201",
        filterId: "HEPA-02",
        roomId: "CR-2107",
        reading: 205,
        runningHours: 6100,
        equipmentStatus: "带病运行",
        note: "超过区域上限 200Pa",
        inspector: "巡检员",
        createdAt: daysAgoIso(5),
        revisions: [],
      },
      {
        id: "INSP-SEED-0202",
        filterId: "HEPA-02",
        roomId: "CR-2107",
        reading: 209,
        runningHours: 6220,
        equipmentStatus: "带病运行",
        note: "更换前锁定基准读数",
        inspector: "厂务工程师",
        createdAt: daysAgoIso(1),
        revisions: [],
      },
      {
        id: "INSP-SEED-0301",
        filterId: "HEPA-03",
        roomId: "Y-0302",
        reading: 152,
        runningHours: 3300,
        equipmentStatus: "正常运行",
        note: "稳定",
        inspector: "巡检员",
        createdAt: daysAgoIso(6),
        revisions: [],
      },
      {
        id: "INSP-SEED-0401",
        filterId: "HEPA-04",
        roomId: "CR-1201",
        reading: 168,
        runningHours: 5900,
        equipmentStatus: "带病运行",
        note: "在用批次已过期，建议安排更换",
        inspector: "巡检员",
        createdAt: daysAgoIso(3),
        revisions: [],
      },
      {
        id: "INSP-SEED-0300",
        filterId: "HEPA-03",
        roomId: "Y-0302",
        reading: 231,
        runningHours: 2860,
        equipmentStatus: "带病运行",
        note: "历史超限记录（已更换复测关闭）",
        inspector: "巡检员",
        createdAt: daysAgoIso(60),
        revisions: [],
      },
      {
        id: "INSP-SEED-0300R",
        filterId: "HEPA-03",
        roomId: "Y-0302",
        reading: 148,
        runningHours: 2870,
        equipmentStatus: "正常运行",
        note: "更换后复测",
        inspector: "厂务工程师",
        createdAt: daysAgoIso(58),
        revisions: [],
      },
    ],
    orders: [
      {
        id: "WO-SEED-01",
        filterId: "HEPA-01",
        roomId: "CR-1201",
        reason: "连续上升",
        status: "待派工",
        assignee: null,
        lockedReading: null,
        lockedRunningHours: null,
        lockedInspectionId: null,
        oldBatchId: null,
        newBatchId: null,
        retestInspectionId: null,
        createdAt: daysAgoIso(2, 10),
        createdBy: "巡检员",
        events: [
          {
            at: daysAgoIso(2, 10),
            by: "系统",
            type: "自动建单",
            detail: "最近 3 次读数连续上升（触发巡检 INSP-SEED-0103）",
          },
        ],
      },
      {
        id: "WO-SEED-02",
        filterId: "HEPA-02",
        roomId: "CR-2107",
        reason: "超过上限",
        status: "更换中",
        assignee: "张工",
        lockedReading: 209,
        lockedRunningHours: 6220,
        lockedInspectionId: "INSP-SEED-0202",
        oldBatchId: "B2026-02",
        newBatchId: null,
        retestInspectionId: null,
        createdAt: daysAgoIso(5, 9),
        createdBy: "巡检员",
        events: [
          { at: daysAgoIso(5, 9), by: "系统", type: "自动建单", detail: "读数 205Pa 超过区域上限 200Pa（触发巡检 INSP-SEED-0201）" },
          { at: daysAgoIso(4, 14), by: "厂务工程师", type: "派工", detail: "派发给 张工" },
          { at: daysAgoIso(1, 8), by: "厂务工程师", type: "锁定读数", detail: "锁定读数 209Pa / 运行 6220h（巡检 INSP-SEED-0202）" },
        ],
      },
      {
        id: "WO-SEED-03",
        filterId: "HEPA-03",
        roomId: "Y-0302",
        reason: "超过上限",
        status: "已关闭",
        assignee: "李工",
        lockedReading: 231,
        lockedRunningHours: 2860,
        lockedInspectionId: "INSP-SEED-0300",
        oldBatchId: "B2025-08",
        newBatchId: "B2026-02",
        retestInspectionId: "INSP-SEED-0300R",
        createdAt: daysAgoIso(61, 9),
        createdBy: "巡检员",
        events: [
          { at: daysAgoIso(61, 9), by: "系统", type: "自动建单", detail: "读数 231Pa 超过区域上限 220Pa" },
          { at: daysAgoIso(60, 10), by: "厂务工程师", type: "完成更换", detail: "释放旧批次 B2025-08，占用新批次 B2026-02，等待复测" },
          { at: daysAgoIso(58, 9), by: "厂务工程师", type: "复测通过关闭", detail: "复测 148Pa 低于锁定值且在限值内" },
        ],
      },
    ],
  };
}
